### ISSUE TITLE
Better handle UI failures

### ISSUE THREAD

**Issue by jswope00** [jswope00/AI-Microapp-Template-Assistant#4]
When a user does not pass a step, they have the chance to try again. But it isn't super clear that they are supposed to try again, and that they should use the original input box to do so. Think about this logic and improvements.

**Comment by rajaathota72-fc** [comment]
Check video here : https://www.youtube.com/watch?v=UM4Pd27Rbyg

**Comment by jswope00** [comment]
Yep, I'm good with this!
