### ISSUE TITLE
Getting Unexpected Application Error in Streamlit

### ISSUE THREAD

**Issue by jswope00** [jswope00/AI-Microapp-Template-Assistant#6]
This app is now throwing an error in streamlit: 
<img width="1699" alt="image" src="https://github.com/jswope00/AI-Microapp-Template-Assistant/assets/1486185/323d439d-96ce-4860-bffe-8d6816eff049">
@rajaathota72-fc can you diagnose?

**Comment by rajaathota72-fc** [comment]
It is corrected now ! the issue is that assitant id was generated by me and openai api key belongs to you ! Now i have corrected the open ai key and assistant id !! 

If you want to have your openai key run once locally so that assitants_id.txt updates to id on your platform.

**Comment by jswope00** [comment]
@rajaathota72-fc how is this one supposed to work? 

I have run it locally, and got the same "Assistant ID not found" error. 
then I deleted the assistnat Id from assistant_id.txt, and got a " module 'openai' has no attribute 'assistants'" error.
Then I deleted the entire assistant_id.txt file and got the same error: 

<img width="1067" alt="image" src="https://github.com/jswope00/AI-Microapp-Template-Assistant/assets/1486185/dacfbd7b-45dd-4d7c-822b-14d4055e6464">

**Comment by rajaathota72-fc** [comment]
Now I have pushed the new version, it should be beta.assistants and beta.threads

**Comment by jswope00** [comment]
Great. 

Also, I was getting this error: 
<img width="1099" alt="image" src="https://github.com/jswope00/AI-Microapp-Template-Assistant/assets/1486185/0d56525e-0964-419c-a8bd-cd876cc64f28">


So I made this change to change file_search to retrieval: 
<img width="265" alt="image" src="https://github.com/jswope00/AI-Microapp-Template-Assistant/assets/1486185/f9b6e8ea-23a8-4103-938c-2017acc81b21">


OK by you?

**Comment by rajaathota72-fc** [comment]
Yeah that would work straightforward ! My Id has access to file search and it was working fine. Actually file search is in beta and may be not accessible for everyone or having issues.

**Comment by jswope00** [comment]
Ah ok. this might address my other issue I wrote in here. Let me try looking at my key and see if I can get back to using v2. For you, are you able to use the 4o model?

**Comment by jswope00** [comment]
OK I figured all this out. I had an old openai package (1.17). Upgrading to the latest (1.30) fixed all.
